import { useState } from 'react';import { Eye,EyeOff,ArrowUpRight,KeyRound } from 'lucide-react';
import { Modal } from './Modal';import { api,post,put } from './api';import type { Provider,Prompt,Protocol,Run } from '../shared/types';
function previewURL(endpoint:string,protocol:Protocol){try{const u=new URL(endpoint);const p=u.pathname.replace(/\/+$/,'');const suffix=protocol==='openai'?'/chat/completions':'/messages';if(p.endsWith('/chat/completions')||p.endsWith('/messages'))u.pathname=p;else u.pathname=p+(p.endsWith('/v1')?'':'/v1')+suffix;return u.toString();}catch{return '填写地址后显示实际请求 URL';}}
export function ProviderEditor({provider,onClose,onSave}:{provider?:Provider;onClose:()=>void;onSave:(p:Provider)=>void}){
 const [name,setName]=useState(provider?.name||''),[protocol,setProtocol]=useState<Protocol>(provider?.protocol||'openai'),[endpoint,setEndpoint]=useState(provider?.endpoint||''),[key,setKey]=useState(''),[models,setModels]=useState(provider?.models.join('\n')||''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const value={name,protocol,endpoint,key,models:models.split(/[\n,，]/).map(v=>v.trim()).filter(Boolean)};const p=provider?await put<Provider>(`/providers/${provider.id}`,value):await post<Provider>('/providers',value);onSave(p);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={provider?'编辑中转站':'添加中转站'} onClose={onClose}><form onSubmit={save} className="editor-form"><label>中转站名称<input aria-label="中转站名称" placeholder="例如：我的主力中转站" value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label><label>接口协议<select aria-label="接口协议" value={protocol} onChange={e=>setProtocol(e.target.value as Protocol)}><option value="openai">OpenAI · Chat Completions</option><option value="anthropic">Anthropic · Messages</option></select></label><label>Endpoint<input aria-label="Endpoint" type="url" placeholder="https://your-relay.com/v1" value={endpoint} onChange={e=>setEndpoint(e.target.value)} required/></label><div className="endpoint-preview"><ArrowUpRight size={14}/><span>{previewURL(endpoint,protocol)}</span></div><label>API key<div className="password-field"><input aria-label="API key" type={show?'text':'password'} placeholder={provider?'留空保留已保存的密钥':'sk-…'} autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} required={!provider}/><button type="button" className="icon-button" aria-label={show?'隐藏密钥':'显示密钥'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><p className="hint"><KeyRound size={13}/> 加密保存在本机，导出结果不包含密钥。</p><label>模型 ID<textarea aria-label="模型 ID" rows={4} placeholder={'每行一个，或用逗号分隔\ngpt-4.1\nclaude-sonnet-4-5'} value={models} onChange={e=>setModels(e.target.value)} required/></label><p className="hint">使用中转站提供的准确模型 ID。保存后可尝试获取 OpenAI 模型列表。</p>{error&&<div className="inline-error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" onClick={onClose}>取消</button><button className="primary" disabled={busy} type="submit">{busy?'保存中…':'保存中转站'}</button></div></form></Modal>;
}
export function PromptEditor({prompt,onClose,onSave}:{prompt:Prompt;onClose:()=>void;onSave:(p:Prompt)=>void}){
 const [name,setName]=useState(prompt.name),[system,setSystem]=useState(prompt.system),[text,setText]=useState(prompt.text),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(copy:boolean){setBusy(true);setError('');try{const body={name,system,text,category:copy?'自定义':prompt.category,description:prompt.description};onSave(copy?await post<Prompt>('/prompts',body):await put<Prompt>('/prompts/'+prompt.id,body));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={prompt.builtin?'预制测试模板':'编辑测试模板'} wide onClose={onClose}><div className="editor-form"><div className="template-meta"><span className="tag">{prompt.category}</span><span className="mono">v{prompt.version}</span><span>{prompt.description}</span></div><label>模板名称<input aria-label="模板名称" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label>系统提示词<textarea aria-label="系统提示词" rows={3} value={system} onChange={e=>setSystem(e.target.value)}/></label><label>测试内容<textarea aria-label="测试内容" className="prompt-input" rows={10} value={text} onChange={e=>setText(e.target.value)}/></label><p className="hint">预制模板保留原版。另存后可以反复编辑，每次保存会增加版本号。</p>{error&&<div className="inline-error" role="alert">{error}</div>}<div className="modal-actions"><button onClick={onClose}>关闭</button>{!prompt.builtin&&<button disabled={busy||!text.trim()||!name.trim()} onClick={()=>save(false)}>保存修改</button>}<button className="primary" disabled={busy||!text.trim()||!name.trim()} onClick={()=>save(true)}>另存为自定义模板</button></div></div></Modal>;
}
export function ReplayEditor({run,providers,onClose,onSave}:{run:Run;providers:Provider[];onClose:()=>void;onSave:(r:Run)=>void}){
 const [bindings,setBindings]=useState<Record<string,string>>(()=>Object.fromEntries(run.snapshot.targets.map((t,i)=>[String(i),providers.some(p=>p.id===t.providerId&&p.protocol===t.protocol)?t.providerId:'']))),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function replay(){setBusy(true);setError('');try{onSave(await post<Run>(`/runs/${run.id}/replay`,{bindings}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title="按原配置重跑" onClose={onClose}><p className="modal-description">将创建一个新实验，保留原来的模型、prompt、endpoint 和实际请求。请选择用于此次调用的凭据。</p><div className="editor-form">{run.snapshot.targets.map((t,i)=><div className="binding" key={i}><b>{t.name} <span className="mono">/ {t.model}</span></b><span className="binding-url">{t.endpoint}</span><label>使用凭据<select aria-label={`目标 ${i+1} 的凭据`} value={bindings[i]} onChange={e=>setBindings({...bindings,[i]:e.target.value})}><option value="">请选择中转站凭据</option>{providers.filter(p=>p.protocol===t.protocol).map(p=><option key={p.id} value={p.id}>{p.name} · {p.endpoint}</option>)}</select></label></div>)}<p className="hint">凭据将发送到上方显示的原 endpoint。所选中转站的新 endpoint 不会替换历史地址。</p>{error&&<div role="alert" className="inline-error">{error}</div>}<div className="modal-actions"><button onClick={onClose}>取消</button><button className="primary" disabled={busy||run.snapshot.targets.some((_,i)=>!bindings[i])} onClick={replay}>{busy?'启动中…':'确认重跑'}</button></div></div></Modal>;
}
export async function remove(path:string){await api(path,{method:'DELETE'});}
